name: status

on:
  pull_request:

jobs:
  lint:
    name: lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - run: pnpm run lint:check:all
        shell: bash

  typecheck:
    name: typecheck

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - run: pnpm run typecheck
        shell: bash
